# Generated by Django 4.2.1 on 2023-05-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_rating_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(related_name='tags', to='catalog.product'),
        ),
    ]
