# Generated by Django 4.2.1 on 2023-05-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_count_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count_products',
        ),
    ]
