# Generated by Django 4.2.1 on 2023-05-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_count_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_products',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(default='', max_length=128, verbose_name='тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(default='', max_length=128, verbose_name='тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=128, verbose_name='статус'),
        ),
    ]
