# Generated by Django 4.2.1 on 2023-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0004_order_count_products_alter_order_deliverytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountProductinOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('order', models.ManyToManyField(to='orders.order')),
                ('product', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
