# Generated by Django 4.2.1 on 2023-05-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_countproductinorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count_products',
        ),
    ]
