# Generated by Django 4.2.1 on 2023-05-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_count_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countproductinorder',
            name='order',
        ),
        migrations.AddField(
            model_name='countproductinorder',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
            preserve_default=False,
        ),
    ]
