# Generated by Django 4.2.1 on 2023-05-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0007_remove_countproductinorder_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countproductinorder',
            name='product',
        ),
        migrations.AddField(
            model_name='countproductinorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
            preserve_default=False,
        ),
    ]
